Updated profiles to new bioschemas types and fixed some typos
nfdi4plants/isa-ro-crate-profile pull request #1
Opened 2024-01-31 10:01 UTC by floWetzels

I updated the profile according to the new bioschemas type and specification adaptations. I also fixed some typos/bugs and added bioschemas/schema.org tags before type names. Please have a look, @HLWeil @stuzart

2024-02-05 10:33 UTC, HLWeil requested changes
Links look really good like this!

2024-02-05 10:33 UTC, HLWeil commented on profile/isa_ro_crate.md
>  |@type |MUST|Text|must be 'File' or 'MediaObject'|
Add link to types here like with the other profiles.

2024-02-05 10:33 UTC, HLWeil commented on profile/isa_ro_crate.md
>  ### LabProcess (_new type_)
The `new type` is not needed anymore I think.

2024-02-05 10:33 UTC, HLWeil commented on profile/isa_ro_crate.md
> +Has the new suggested Bioschemas [bioschemas.org/LabProcess](https://bioschemas.org/LabProcess) type and maps to the [ISA-JSON Process](https://isa-specs.readthedocs.io/en/latest/isajson.html#process
Maybe change to `Has the Bioschemas DRAFT type and...`

2024-02-05 10:33 UTC, HLWeil commented on profile/isa_ro_crate.md
> +Has the new suggested Bioschemas [bioschemas.org/LabProcess](https://bioschemas.org/LabProcess) type and maps to the [ISA-JSON Process](https://isa-specs.readthedocs.io/en/latest/isajson.html#process
Not necessary, but the LabProcess is on the same level like LabProtocol and such now.

2024-02-27 09:36 UTC, merged

2024-02-27 15:29 UTC, stuzart reviewed
sorry, I only just spotted this but looks good